Models/NhmBook.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace NhmLesson06CF.Models
{
    public class NhmBook
    {
        [Key]
        public int NhmID { get; set; }
        public string NhmBookId { get; set; }
        public string NhmTitle { get; set; }
        public string NhmAuthor { get; set; }
        public int NhmYear { get; set; }
        public string NhmPulisher { get; set; }
        public string NhmPicture { get; set; }
        public int NhmCategoryId { get; set; }
        //thuoc tinh quan he
        public virtual NhmCategory NhmCategory { get; set; }
    }
}

Models/NhmBookstore.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace NhmLesson06CF.Models
{
    public class NhmBookstore : DbContext
    {
        public NhmBookstore():base("NhmBookStoreConnectionString") {}
    //khai bai cac thuoc tinh tuong ung voi cac bang trong csdl
    public DbSet<NhmCategory> NhmCategories { get; set; }
    public DbSet<NhmBook> NhmBooks { get; set; }

    }
}

Models/NhmCategory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace NhmLesson06CF.Models
{
    public class NhmCategory
    {
        [Key]
        public int NhmId { get; set; }
        public string NhmCategoryName { get; set; }
        //thuoc tinh quan he
        public virtual ICollection<NhmBook> NhmBooks { get; set; }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NhmLesson06CF.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/NhmBooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NhmLesson06CF.Models;

namespace NhmLesson06CF.Controllers
{
    public class NhmBooksController : Controller
    {
        private NhmBookstore db = new NhmBookstore();

        // GET: NhmBooks
        public ActionResult Index()
        {
            return View(db.NhmBooks.ToList());
        }

        // GET: NhmBooks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhmBook nhmBook = db.NhmBooks.Find(id);
            if (nhmBook == null)
            {
                return HttpNotFound();
            }
            return View(nhmBook);
        }

        // GET: NhmBooks/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: NhmBooks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "NhmID,NhmBookId,NhmTitle,NhmAuthor,NhmYear,NhmPulisher,NhmPicture,NhmCategoryId")] NhmBook nhmBook)
        {
            if (ModelState.IsValid)
            {
                db.NhmBooks.Add(nhmBook);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(nhmBook);
        }

        // GET: NhmBooks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhmBook nhmBook = db.NhmBooks.Find(id);
            if (nhmBook == null)
            {
                return HttpNotFound();
            }
            return View(nhmBook);
        }

        // POST: NhmBooks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "NhmID,NhmBookId,NhmTitle,NhmAuthor,NhmYear,NhmPulisher,NhmPicture,NhmCategoryId")] NhmBook nhmBook)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nhmBook).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(nhmBook);
        }

        // GET: NhmBooks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhmBook nhmBook = db.NhmBooks.Find(id);
            if (nhmBook == null)
            {
                return HttpNotFound();
            }
            return View(nhmBook);
        }

        // POST: NhmBooks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            NhmBook nhmBook = db.NhmBooks.Find(id);
            db.NhmBooks.Remove(nhmBook);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/NhmCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations;
using System.Web;
using System.Web.Mvc;
using NhmLesson06CF.Models;


namespace NhmLesson06CF.Controllers
{
    public class NhmCategoryController : Controller
    {
        private static NhmBookstore nhmDb;
        public NhmCategoryController()
        {
            nhmDb = new NhmBookstore();
        }
        public ActionResult NhmIndex()
        {
            /*
             * Khoi tao DbContext
             * Ef se tim thong tin ket noi trong file machinee.config cua .net framework tren nay
             * va sau do tao csdl
             * */
            NhmBookstore nhmDb = new NhmBookstore();
            var nhmCategories = nhmDb.NhmCategories.ToList();
            return View(nhmCategories);
        }
        public ActionResult NhmCreate()
        {
            var nhmcategory = new NhmCategory();
            return View(nhmcategory);
        }
        [HttpPost]
        public ActionResult NhmCreate(NhmCategory nhmCategory)
        {
            nhmDb.NhmCategories.Add(nhmCategory);
            nhmDb.SaveChanges();

            return RedirectToAction("NhmIndex");
        }
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Views/NhmBooks/Create.cshtml
@model NhmLesson06CF.Models.NhmBook

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>NhmBook</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NhmBookId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NhmBookId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NhmBookId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NhmTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NhmTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NhmTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NhmAuthor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NhmAuthor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NhmAuthor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NhmYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NhmYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NhmYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NhmPulisher, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NhmPulisher, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NhmPulisher, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NhmPicture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NhmPicture, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NhmPicture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NhmCategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NhmCategoryId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NhmCategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/NhmBooks/Delete.cshtml
@model NhmLesson06CF.Models.NhmBook

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>NhmBook</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NhmBookId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NhmBookId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NhmTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NhmTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NhmAuthor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NhmAuthor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NhmYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NhmYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NhmPulisher)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NhmPulisher)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NhmPicture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NhmPicture)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NhmCategoryId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NhmCategoryId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/NhmBooks/Details.cshtml
@model NhmLesson06CF.Models.NhmBook

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>NhmBook</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NhmBookId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NhmBookId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NhmTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NhmTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NhmAuthor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NhmAuthor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NhmYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NhmYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NhmPulisher)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NhmPulisher)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NhmPicture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NhmPicture)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NhmCategoryId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NhmCategoryId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.NhmID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/NhmBooks/Edit.cshtml
@model NhmLesson06CF.Models.NhmBook

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>NhmBook</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.NhmID)

        <div class="form-group">
            @Html.LabelFor(model => model.NhmBookId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NhmBookId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NhmBookId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NhmTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NhmTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NhmTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NhmAuthor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NhmAuthor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NhmAuthor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NhmYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NhmYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NhmYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NhmPulisher, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NhmPulisher, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NhmPulisher, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NhmPicture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NhmPicture, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NhmPicture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NhmCategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NhmCategoryId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NhmCategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/NhmBooks/Index.cshtml
@model IEnumerable<NhmLesson06CF.Models.NhmBook>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NhmBookId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NhmTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NhmAuthor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NhmYear)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NhmPulisher)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NhmPicture)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NhmCategoryId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NhmBookId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NhmTitle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NhmAuthor)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NhmYear)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NhmPulisher)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NhmPicture)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NhmCategoryId)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.NhmID }) |
            @Html.ActionLink("Details", "Details", new { id=item.NhmID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.NhmID })
        </td>
    </tr>
}

</table>

Views/NhmCategory/NhmCreate.cshtml
@model NhmLesson06CF.Models.NhmCategory

@{
    ViewBag.Title = "NhmCreate";
}

<h2>NhmCreate</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>NhmCategory</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NhmCategoryName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NhmCategoryName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NhmCategoryName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/NhmCategory/NhmIndex.cshtml
@model IEnumerable<NhmLesson06CF.Models.NhmCategory>

@{
    ViewBag.Title = "NhmIndex";
}

<h2>NhmIndex</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NhmCategoryName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NhmCategoryName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.NhmId }) |
            @Html.ActionLink("Details", "Details", new { id=item.NhmId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.NhmId })
        </td>
    </tr>
}

</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Ngô Hoàng Minh</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Ngô Hoàng Minh", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "navbar-brand" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "navbar-brand" })</li>
                    <li>@Html.ActionLink("Nhm: Category", "NhmIndex", "NhmCategories", new { area = "" }, new { @class = "navbar-brand" })</li>
                    <li>@Html.ActionLink("Nhm: Book", "Index", "NhmBooks", new { area = "" }, new { @class = "navbar-brand" })</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>